function pde = ex05_1_SFdata(para)
pde = struct('Mphi',para.Mphi, ...
             'Mrho',para.Mrho, ...
             'epsilon',para.epsilon, ...
             'eta',para.eta, ...
             'gamma',para.gamma, ...
             'gamma1',para.gamma1, ...
             'gamma2',para.gamma2, ...
             'Lambda_1',para.Lambda_1,...
             'Lambda_2',para.Lambda_2,...
             'alpha',para.alpha,...
             'alpha1',para.alpha1,...
             'alpha2',para.alpha2,...
             'Sigma',para.Sigma,...
             'upsilon',para.upsilon,...
             'theta',para.theta, ...
             'theta1',para.theta1, ...
             'theta2',para.theta2, ...
             'rhos',para.rhos, ...
             'beta',para.beta,...
             'xi',para.xi, ...
             'S1',para.S1, ...
             'S2',para.S2, ...
             'C0',para.C0, ...
             'init_phi',@init_phi, ...
             'init_rho',@init_rho, ...
             'init_u',@init_u,...
             'init_v',@init_v,...
             'init_p',@init_p,...
             'name','ex05_1_SFdata');

    function z = init_phi(x,y)
        [nx, ny] = size(x);
        phibar = 0;
        rng(1,"philox")
        z = phibar + 0.001 * (2*rand(nx,ny)-1);
    end

    function z = init_rho(x,y) 
        [nx, ny] = size(x);
        rhobar = 0.2;
        z = rhobar + 0.001 * (2*rand(nx,ny)-1);
    end
    function z = init_u(x,y)
        z = zeros(size(x));
    end
    function z = init_v(x,y)
        z = zeros(size(x));
    end    
    function z = init_p(x,y)
        z = zeros(size(x));
    end
end