function pde = ex03_2_SFdata(para)
pde = struct('Mphi',para.Mphi, ...
             'Mrho',para.Mrho, ...
             'epsilon',para.epsilon, ...
             'eta',para.eta, ...
             'gamma1',para.gamma1, ...
             'gamma2',para.gamma2, ...
             'alpha1',para.alpha1,...
             'alpha2',para.alpha2,...
             'Sigma',para.Sigma,...
             'upsilon',para.upsilon,...
             'Lambda_1',para.Lambda_1,...
             'Lambda_2',para.Lambda_2,...
             'theta',para.theta, ...
             'beta',para.beta,...
             'xi',para.xi, ...
             'S1',para.S1, ...
             'S2',para.S2, ...
             'C0',para.C0, ...
             'init_phi',@init_phi, ...
             'init_rho',@init_rho, ...
             'init_u',@init_u,...
             'init_v',@init_v,...
             'init_p',@init_p,...
             'name','ex03_2_SFdata');

    function z = init_phi(x,y)
        rl = [0.28*pi, 0.28*pi];
        xl = [pi, pi];
        yl = [1.305*pi, 0.695*pi];
        
        z =1+ tanh((rl(1) - sqrt((x - xl(1)) .^ 2 + (y - yl(1)) .^ 2)) / (1.5 * pde.epsilon)) + ...
            tanh((rl(2) - sqrt((x - xl(2)) .^ 2 + (y - yl(2)) .^ 2)) / (1.5 * pde.epsilon));
    end

    function z = init_rho(x,y) 
        [nx, ny] = size(x);
        rhobar = 0.2;
        z = rhobar.* ones(nx,ny); % + 0.001 * (2*rand(nx,ny)-1);
    end
    function z = init_u(x,y)
        z = zeros(size(x));
    end
    function z = init_v(x,y)
        z = zeros(size(x));
    end    
    function z = init_p(x,y)
        z = zeros(size(x));
    end
end